from __future__ import division
from math import degrees


"""
Parameters in:

Distance: METERS
Angles: RADIANS
Speed: METER PER SECOND
"""
CAMERA_HEIGHT_FROM_FLOOR = 0.39  # CHANGE NEEDED

TARGET_HEIGHT_FROM_FLOOR = 2.18 # CHANGE NEEDED
TARGET_HEIGHT = 0.1016
TARGET_WIDTH = 0.4106 # CHANGE NEEDED
TARGET_ASPECT_RATIO = TARGET_WIDTH / TARGET_HEIGHT

SHOOTER_HEIGHT = 0.41  # CHANGE NEEDED
SHOOTER_SPEED = 10  # CHANGE NEEDED
CAMERA2SHOOTER_XDIFFERENCE = 0

RESIZE_FACTOR = 1
