from __future__ import division
from math import degrees


"""
Parameters in:

Distance: METERS
Angles: RADIANS
Speed: METER PER SECOND
"""
CAMERA_HEIGHT_FROM_FLOOR = 0.1

TARGET_HEIGHT_FROM_FLOOR = 2.1336
TARGET_HEIGHT = 0.1016
TARGET_WIDTH = 0.39788 # 0.381 in real arena
TARGET_ASPECT_RATIO = TARGET_WIDTH / TARGET_HEIGHT
LIFT_TARGET_HEIGHT = 0.13

SHOOTER_HEIGHT = 0.24
SHOOTER_SPEED = 10  # CHANGE NEEDED
CAMERA2SHOOTER_XDIFFERENCE = 0.04

RESIZE_FACTOR = 0.5
BRIGHTNESS = -0.4
